#spring:
#  h2:
#    console:
#      anabled: true
#      settings:
#        trace: false
#        web-allow-others: false
#  datasource:
#    url: jdbc:h2:mem:credit_sistem_db
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:credit_sistem_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
